# Upbit Open API
#
# ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
#
# OpenAPI spec version: 1.0.0
# Contact: ujhin942@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DepositCompleteResponse Class
#'
#' @field currency 
#' @field deposit_address 
#' @field secondary_address 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DepositCompleteResponse <- R6::R6Class(
  'DepositCompleteResponse',
  public = list(
    `currency` = NULL,
    `deposit_address` = NULL,
    `secondary_address` = NULL,
    initialize = function(`currency`, `deposit_address`, `secondary_address`){
      if (!missing(`currency`)) {
        stopifnot(is.character(`currency`), length(`currency`) == 1)
        self$`currency` <- `currency`
      }
      if (!missing(`deposit_address`)) {
        stopifnot(is.character(`deposit_address`), length(`deposit_address`) == 1)
        self$`deposit_address` <- `deposit_address`
      }
      if (!missing(`secondary_address`)) {
        stopifnot(is.character(`secondary_address`), length(`secondary_address`) == 1)
        self$`secondary_address` <- `secondary_address`
      }
    },
    toJSON = function() {
      DepositCompleteResponseObject <- list()
      if (!is.null(self$`currency`)) {
        DepositCompleteResponseObject[['currency']] <- self$`currency`
      }
      if (!is.null(self$`deposit_address`)) {
        DepositCompleteResponseObject[['deposit_address']] <- self$`deposit_address`
      }
      if (!is.null(self$`secondary_address`)) {
        DepositCompleteResponseObject[['secondary_address']] <- self$`secondary_address`
      }

      DepositCompleteResponseObject
    },
    fromJSON = function(DepositCompleteResponseJson) {
      DepositCompleteResponseObject <- jsonlite::fromJSON(DepositCompleteResponseJson)
      if (!is.null(DepositCompleteResponseObject$`currency`)) {
        self$`currency` <- DepositCompleteResponseObject$`currency`
      }
      if (!is.null(DepositCompleteResponseObject$`deposit_address`)) {
        self$`deposit_address` <- DepositCompleteResponseObject$`deposit_address`
      }
      if (!is.null(DepositCompleteResponseObject$`secondary_address`)) {
        self$`secondary_address` <- DepositCompleteResponseObject$`secondary_address`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "currency": %s,
           "deposit_address": %s,
           "secondary_address": %s
        }',
        self$`currency`,
        self$`deposit_address`,
        self$`secondary_address`
      )
    },
    fromJSONString = function(DepositCompleteResponseJson) {
      DepositCompleteResponseObject <- jsonlite::fromJSON(DepositCompleteResponseJson)
      self$`currency` <- DepositCompleteResponseObject$`currency`
      self$`deposit_address` <- DepositCompleteResponseObject$`deposit_address`
      self$`secondary_address` <- DepositCompleteResponseObject$`secondary_address`
    }
  )
)
