/*
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UpbitOpenApi) {
      root.UpbitOpenApi = {};
    }
    root.UpbitOpenApi.APIKey = factory(root.UpbitOpenApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The APIKey model module.
   * @module model/APIKey
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>APIKey</code>.
   * @alias module:model/APIKey
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>APIKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIKey} obj Optional instance to populate.
   * @return {module:model/APIKey} The populated <code>APIKey</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('access_key'))
        obj.accessKey = ApiClient.convertToType(data['access_key'], 'String');
      if (data.hasOwnProperty('expire_at'))
        obj.expireAt = ApiClient.convertToType(data['expire_at'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} accessKey
   */
  exports.prototype.accessKey = undefined;

  /**
   * @member {String} expireAt
   */
  exports.prototype.expireAt = undefined;


  return exports;

}));
