/**
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

#ifndef _SWG_SWGTradeApi_H_
#define _SWG_SWGTradeApi_H_

#include "SWGHttpRequest.h"

#include <QString>
#include "SWGError.h"
#include "SWGNumber.h"
#include "SWGObject.h"

#include <QObject>

namespace Swagger {

class SWGTradeApi: public QObject {
    Q_OBJECT

public:
    SWGTradeApi();
    SWGTradeApi(QString host, QString basePath);
    ~SWGTradeApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void trade_ticker(QString* markets);
    void trade_ticks(QString* market, QString* to, SWGNumber* count, QString* cursor, SWGNumber* days_ago);
    
private:
    void trade_tickerCallback (SWGHttpRequestWorker * worker);
    void trade_ticksCallback (SWGHttpRequestWorker * worker);
    
signals:
    void trade_tickerSignal(SWGObject* summary);
    void trade_ticksSignal(SWGObject* summary);
    
    void trade_tickerSignalE(SWGObject* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void trade_ticksSignalE(SWGObject* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void trade_tickerSignalEFull(SWGHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void trade_ticksSignalEFull(SWGHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
