/**
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGWallet.h
 *
 * 
 */

#ifndef SWGWallet_H_
#define SWGWallet_H_

#include <QJsonObject>


#include "SWGNumber.h"
#include <QString>

#include "SWGObject.h"

namespace Swagger {

class SWGWallet: public SWGObject {
public:
    SWGWallet();
    SWGWallet(QString json);
    ~SWGWallet();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    SWGWallet* fromJson(QString jsonString) override;

    QString* getCurrency();
    void setCurrency(QString* currency);

    QString* getWalletState();
    void setWalletState(QString* wallet_state);

    QString* getBlockState();
    void setBlockState(QString* block_state);

    SWGNumber* getBlockHeight();
    void setBlockHeight(SWGNumber* block_height);

    QString* getBlockUpdatedAt();
    void setBlockUpdatedAt(QString* block_updated_at);


    virtual bool isSet() override;

private:
    QString* currency;
    bool m_currency_isSet;

    QString* wallet_state;
    bool m_wallet_state_isSet;

    QString* block_state;
    bool m_block_state_isSet;

    SWGNumber* block_height;
    bool m_block_height_isSet;

    QString* block_updated_at;
    bool m_block_updated_at_isSet;

};

}

#endif /* SWGWallet_H_ */
