#import <Foundation/Foundation.h>
#import "SWGError.h"
#import "SWGApi.h"

/**
* Upbit Open API
* ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
*
* OpenAPI spec version: 1.0.0
* Contact: ujhin942@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGMarketApi: NSObject <SWGApi>

extern NSString* kSWGMarketApiErrorDomain;
extern NSInteger kSWGMarketApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 마켓 코드 조회
/// ## 업비트에서 거래 가능한 마켓 목록 
///
/// @param isDetails 유의종목 필드과 같은 상세 정보 노출 여부(선택 파라미터)  (optional) (default to false)
/// 
///  code:200 message:"OK",
///  code:400 message:"Status: Bad Request ",
///  code:401 message:"Status: Unauthorized ",
///  code:403 message:"Status: Forbidden ",
///  code:404 message:"Status: Not Found ",
///  code:429 message:"Too Many Requests",
///  code:500 message:"Status: Internal Server Error "
///
/// @return NSObject*
-(NSURLSessionTask*) marketInfoAllWithIsDetails: (NSNumber*) isDetails
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;



@end
