--[[
  Upbit Open API
 
  ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 
  OpenAPI spec version: 1.0.0
  Contact: ujhin942@gmail.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- error class
local error = {}
local error_mt = {
	__name = "error";
	__index = error;
}

local function cast_error(t)
	return setmetatable(t, error_mt)
end

local function new_error(error)
	return cast_error({
		["error"] = error;
	})
end

return {
	cast = cast_error;
	new = new_error;
}
