--[[
  Upbit Open API
 
  ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 
  OpenAPI spec version: 1.0.0
  Contact: ujhin942@gmail.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- member_level class
local member_level = {}
local member_level_mt = {
	__name = "member_level";
	__index = member_level;
}

local function cast_member_level(t)
	return setmetatable(t, member_level_mt)
end

local function new_member_level(security_level, fee_level, email_verified, identity_auth_verified, bank_account_verified, kakao_pay_auth_verified, locked, wallet_locked)
	return cast_member_level({
		["security_level"] = security_level;
		["fee_level"] = fee_level;
		["email_verified"] = email_verified;
		["identity_auth_verified"] = identity_auth_verified;
		["bank_account_verified"] = bank_account_verified;
		["kakao_pay_auth_verified"] = kakao_pay_auth_verified;
		["locked"] = locked;
		["wallet_locked"] = wallet_locked;
	})
end

return {
	cast = cast_member_level;
	new = new_member_level;
}
