--[[
  Upbit Open API
 
  ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 
  OpenAPI spec version: 1.0.0
  Contact: ujhin942@gmail.com
  Generated by: https://github.com/swagger-api/swagger-codegen.git
]]

-- trade_ticks class
local trade_ticks = {}
local trade_ticks_mt = {
	__name = "trade_ticks";
	__index = trade_ticks;
}

local function cast_trade_ticks(t)
	return setmetatable(t, trade_ticks_mt)
end

local function new_trade_ticks(market, trade_date_utc, trade_time_utc, timestamp, trade_price, trade_volume, prev_closing_price, change_price, ask_bid, sequential_id)
	return cast_trade_ticks({
		["market"] = market;
		["trade_date_utc"] = trade_date_utc;
		["trade_time_utc"] = trade_time_utc;
		["timestamp"] = timestamp;
		["trade_price"] = trade_price;
		["trade_volume"] = trade_volume;
		["prev_closing_price"] = prev_closing_price;
		["change_price"] = change_price;
		["ask_bid"] = ask_bid;
		["sequential_id"] = sequential_id;
	})
end

return {
	cast = cast_trade_ticks;
	new = new_trade_ticks;
}
