/*
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpbitOpenApi);
  }
}(this, function(expect, UpbitOpenApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Market', function() {
      beforeEach(function() {
        instance = new UpbitOpenApi.Market();
      });

      it('should create an instance of Market', function() {
        // TODO: update the code to test Market
        expect(instance).to.be.a(UpbitOpenApi.Market);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property orderTypes (base name: "order_types")', function() {
        // TODO: update the code to test the property orderTypes
        expect(instance).to.have.property('orderTypes');
        // expect(instance.orderTypes).to.be(expectedValueLiteral);
      });

      it('should have the property orderSides (base name: "order_sides")', function() {
        // TODO: update the code to test the property orderSides
        expect(instance).to.have.property('orderSides');
        // expect(instance.orderSides).to.be(expectedValueLiteral);
      });

      it('should have the property bid (base name: "bid")', function() {
        // TODO: update the code to test the property bid
        expect(instance).to.have.property('bid');
        // expect(instance.bid).to.be(expectedValueLiteral);
      });

      it('should have the property ask (base name: "ask")', function() {
        // TODO: update the code to test the property ask
        expect(instance).to.have.property('ask');
        // expect(instance.ask).to.be(expectedValueLiteral);
      });

      it('should have the property maxTotal (base name: "max_total")', function() {
        // TODO: update the code to test the property maxTotal
        expect(instance).to.have.property('maxTotal');
        // expect(instance.maxTotal).to.be(expectedValueLiteral);
      });

      it('should have the property state (base name: "state")', function() {
        // TODO: update the code to test the property state
        expect(instance).to.have.property('state');
        // expect(instance.state).to.be(expectedValueLiteral);
      });

    });
  });

}));
