/*
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpbitOpenApi);
  }
}(this, function(expect, UpbitOpenApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Currency', function() {
      beforeEach(function() {
        instance = new UpbitOpenApi.Currency();
      });

      it('should create an instance of Currency', function() {
        // TODO: update the code to test Currency
        expect(instance).to.be.a(UpbitOpenApi.Currency);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property withdrawFee (base name: "withdraw_fee")', function() {
        // TODO: update the code to test the property withdrawFee
        expect(instance).to.have.property('withdrawFee');
        // expect(instance.withdrawFee).to.be(expectedValueLiteral);
      });

      it('should have the property isCoin (base name: "is_coin")', function() {
        // TODO: update the code to test the property isCoin
        expect(instance).to.have.property('isCoin');
        // expect(instance.isCoin).to.be(expectedValueLiteral);
      });

      it('should have the property walletState (base name: "wallet_state")', function() {
        // TODO: update the code to test the property walletState
        expect(instance).to.have.property('walletState');
        // expect(instance.walletState).to.be(expectedValueLiteral);
      });

      it('should have the property walletSupport (base name: "wallet_support")', function() {
        // TODO: update the code to test the property walletSupport
        expect(instance).to.have.property('walletSupport');
        // expect(instance.walletSupport).to.be(expectedValueLiteral);
      });

    });
  });

}));
