/**
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class Trade (
  // 마켓의 유일 키
  market: Option[String] = None,
  // 체결의 고유 아이디
  uuid: Option[String] = None,
  // 체결 가격
  price: Option[String] = None,
  // 체결 양
  volume: Option[String] = None,
  // 체결된 총 가격
  funds: Option[String] = None,
  // 체결 종류
  side: Option[String] = None,
  // 체결 시각
  createdAt: Option[String] = None
)

