/*
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import io.swagger.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TradeApi
 */
@Ignore
public class TradeApiTest {

    private final TradeApi api = new TradeApi();

    
    /**
     * 시세 Ticker 조회
     *
     * ## 현재가 정보 요청 당시 종목의 스냅샷을 반환한다. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tradeTickerTest() throws ApiException {
        String markets = null;
        Object response = api.tradeTicker(markets);

        // TODO: test validations
    }
    
    /**
     * 시세 체결 조회
     *
     * ## 최근 체결 내역 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tradeTicksTest() throws ApiException {
        String market = null;
        String to = null;
        BigDecimal count = null;
        String cursor = null;
        BigDecimal daysAgo = null;
        Object response = api.tradeTicks(market, to, count, cursor, daysAgo);

        // TODO: test validations
    }
    
}
