<?php
/**
 * TickerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upbit Open API
 *
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com]
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TickerTest Class Doc Comment
 *
 * @category    Class
 * @description Ticker
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TickerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ticker"
     */
    public function testTicker()
    {
    }

    /**
     * Test attribute "market"
     */
    public function testPropertyMarket()
    {
    }

    /**
     * Test attribute "trade_date"
     */
    public function testPropertyTradeDate()
    {
    }

    /**
     * Test attribute "trade_time"
     */
    public function testPropertyTradeTime()
    {
    }

    /**
     * Test attribute "trade_date_kst"
     */
    public function testPropertyTradeDateKst()
    {
    }

    /**
     * Test attribute "trade_time_kst"
     */
    public function testPropertyTradeTimeKst()
    {
    }

    /**
     * Test attribute "opening_price"
     */
    public function testPropertyOpeningPrice()
    {
    }

    /**
     * Test attribute "high_price"
     */
    public function testPropertyHighPrice()
    {
    }

    /**
     * Test attribute "low_price"
     */
    public function testPropertyLowPrice()
    {
    }

    /**
     * Test attribute "trade_price"
     */
    public function testPropertyTradePrice()
    {
    }

    /**
     * Test attribute "prev_closing_price"
     */
    public function testPropertyPrevClosingPrice()
    {
    }

    /**
     * Test attribute "change"
     */
    public function testPropertyChange()
    {
    }

    /**
     * Test attribute "change_price"
     */
    public function testPropertyChangePrice()
    {
    }

    /**
     * Test attribute "change_rate"
     */
    public function testPropertyChangeRate()
    {
    }

    /**
     * Test attribute "signed_change_price"
     */
    public function testPropertySignedChangePrice()
    {
    }

    /**
     * Test attribute "signed_change_rate"
     */
    public function testPropertySignedChangeRate()
    {
    }

    /**
     * Test attribute "trade_volume"
     */
    public function testPropertyTradeVolume()
    {
    }

    /**
     * Test attribute "acc_trade_price"
     */
    public function testPropertyAccTradePrice()
    {
    }

    /**
     * Test attribute "acc_trade_price_24h"
     */
    public function testPropertyAccTradePrice24h()
    {
    }

    /**
     * Test attribute "acc_trade_volume"
     */
    public function testPropertyAccTradeVolume()
    {
    }

    /**
     * Test attribute "acc_trade_volume_24h"
     */
    public function testPropertyAccTradeVolume24h()
    {
    }

    /**
     * Test attribute "highest_52_week_price"
     */
    public function testPropertyHighest52WeekPrice()
    {
    }

    /**
     * Test attribute "highest_52_week_date"
     */
    public function testPropertyHighest52WeekDate()
    {
    }

    /**
     * Test attribute "lowest_52_week_price"
     */
    public function testPropertyLowest52WeekPrice()
    {
    }

    /**
     * Test attribute "lowest_52_week_date"
     */
    public function testPropertyLowest52WeekDate()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }
}
