<?php
/**
 * TradeTicksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upbit Open API
 *
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com]
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TradeTicksTest Class Doc Comment
 *
 * @category    Class
 * @description TradeTicks
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TradeTicksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TradeTicks"
     */
    public function testTradeTicks()
    {
    }

    /**
     * Test attribute "market"
     */
    public function testPropertyMarket()
    {
    }

    /**
     * Test attribute "trade_date_utc"
     */
    public function testPropertyTradeDateUtc()
    {
    }

    /**
     * Test attribute "trade_time_utc"
     */
    public function testPropertyTradeTimeUtc()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "trade_price"
     */
    public function testPropertyTradePrice()
    {
    }

    /**
     * Test attribute "trade_volume"
     */
    public function testPropertyTradeVolume()
    {
    }

    /**
     * Test attribute "prev_closing_price"
     */
    public function testPropertyPrevClosingPrice()
    {
    }

    /**
     * Test attribute "change_price"
     */
    public function testPropertyChangePrice()
    {
    }

    /**
     * Test attribute "ask_bid"
     */
    public function testPropertyAskBid()
    {
    }

    /**
     * Test attribute "sequential_id"
     */
    public function testPropertySequentialId()
    {
    }
}
