/**
* Upbit Open API
* ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
*
* OpenAPI spec version: 1.0.0
* Contact: ujhin942@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param ask_price 매도호가
 * @param bid_price 매수호가
 * @param ask_size 매도 잔량
 * @param bid_size 매수 잔량
 */
data class OrderbookUnit (
    /* 매도호가 */
    val ask_price: kotlin.Double? = null,
    /* 매수호가 */
    val bid_price: kotlin.Double? = null,
    /* 매도 잔량 */
    val ask_size: kotlin.Double? = null,
    /* 매수 잔량 */
    val bid_size: kotlin.Double? = null
) {

}

