#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Upbit Open API
* ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
*
* OpenAPI spec version: 1.0.0
* Contact: ujhin942@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGCandleDate
@end

@interface SWGCandleDate : SWGObject

/* 마켓명 [optional]
 */
@property(nonatomic) NSString* market;
/* 캔들 기준 시각 (UTC 기준) [optional]
 */
@property(nonatomic) NSString* candleDateTimeUtc;
/* 캔들 기준 시각 (KST 기준) [optional]
 */
@property(nonatomic) NSString* candleDateTimeKst;
/* 시가 [optional]
 */
@property(nonatomic) NSNumber* openingPrice;
/* 고가 [optional]
 */
@property(nonatomic) NSNumber* highPrice;
/* 저가 [optional]
 */
@property(nonatomic) NSNumber* lowPrice;
/* 종가 [optional]
 */
@property(nonatomic) NSNumber* tradePrice;
/* 해당 캔들에서 마지막 틱이 저장된 시각 [optional]
 */
@property(nonatomic) NSNumber* timestamp;
/* 누적 거래 금액 [optional]
 */
@property(nonatomic) NSNumber* candleAccTradePrice;
/* 누적 거래량 [optional]
 */
@property(nonatomic) NSNumber* candleAccTradeVolume;
/* 캔들 기간의 가장 첫 날 [optional]
 */
@property(nonatomic) NSString* firstDayOfPeriod;

@end
