#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Upbit Open API
* ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
*
* OpenAPI spec version: 1.0.0
* Contact: ujhin942@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGTrade.h"
@protocol SWGTrade;
@class SWGTrade;



@protocol SWGOrderInfo
@end

@interface SWGOrderInfo : SWGObject

/* 주문의 고유 아이디 [optional]
 */
@property(nonatomic) NSString* uuid;
/* 주문 종류 [optional]
 */
@property(nonatomic) NSString* side;
/* 주문 방식 [optional]
 */
@property(nonatomic) NSString* ordType;
/* 주문 당시 화폐 가격 [optional]
 */
@property(nonatomic) NSString* price;
/* 주문 상태 [optional]
 */
@property(nonatomic) NSString* state;
/* 마켓의 유일키 [optional]
 */
@property(nonatomic) NSString* market;
/* 주문 생성 시간 [optional]
 */
@property(nonatomic) NSString* createdAt;
/* 사용자가 입력한 주문 양 [optional]
 */
@property(nonatomic) NSString* volume;
/* 체결 후 남은 주문 양 [optional]
 */
@property(nonatomic) NSString* remainingVolume;
/* 수수료로 예약된 비용 [optional]
 */
@property(nonatomic) NSString* reservedFee;
/* 남은 수수료 [optional]
 */
@property(nonatomic) NSString* remainingFee;
/* 사용된 수수료 [optional]
 */
@property(nonatomic) NSString* paidFee;
/* 거래에 사용중인 비용 [optional]
 */
@property(nonatomic) NSString* locked;
/* 체결된 양 [optional]
 */
@property(nonatomic) NSString* executedVolume;
/* 해당 주문에 걸린 체결 수 [optional]
 */
@property(nonatomic) NSNumber* tradesCount;
/* 체결 [optional]
 */
@property(nonatomic) NSArray<SWGTrade>* trades;

@end
