#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Upbit Open API
* ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
*
* OpenAPI spec version: 1.0.0
* Contact: ujhin942@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGWithdrawLimit
@end

@interface SWGWithdrawLimit : SWGObject

/* 화폐를 의미하는 영문 대문자 코드 [optional]
 */
@property(nonatomic) NSString* currency;
/* 출금 최소 금액/수량 [optional]
 */
@property(nonatomic) NSString* minimum;
/* 1회 출금 한도 [optional]
 */
@property(nonatomic) NSString* onetime;
/* 1일 출금 한도 [optional]
 */
@property(nonatomic) NSString* daily;
/* 1일 잔여 출금 한도 [optional]
 */
@property(nonatomic) NSString* remainingDaily;
/* 통합 1일 잔여 출금 한도 [optional]
 */
@property(nonatomic) NSString* remainingDailyKrw;
/* 출금 금액/수량 소수점 자리 수 [optional]
 */
@property(nonatomic) NSNumber* fixed;
/* 출금 지원 여부 [optional]
 */
@property(nonatomic) NSNumber* canWithdraw;

@end
