/**
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerModule.h"

IMPLEMENT_MODULE(SwaggerModule, Swagger);
DEFINE_LOG_CATEGORY(LogSwagger);

void SwaggerModule::StartupModule()
{
}

void SwaggerModule::ShutdownModule()
{
}

