/**
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerOrderChance.h"

#include "SwaggerModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerOrderChance::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (BidFee.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("bid_fee")); WriteJsonValue(Writer, BidFee.GetValue());	
	}
	if (AskFee.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("ask_fee")); WriteJsonValue(Writer, AskFee.GetValue());	
	}
	if (Market.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("market")); WriteJsonValue(Writer, Market.GetValue());	
	}
	if (BidAccount.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("bid_account")); WriteJsonValue(Writer, BidAccount.GetValue());	
	}
	if (AskAccount.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("ask_account")); WriteJsonValue(Writer, AskAccount.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerOrderChance::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("bid_fee"), BidFee);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("ask_fee"), AskFee);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("market"), Market);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("bid_account"), BidAccount);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("ask_account"), AskAccount);

	return ParseSuccess;
}
}
