/**
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class MarketInfo {
  
  @SerializedName("market")
  private String market = null;
  @SerializedName("korean_name")
  private String koreanName = null;
  @SerializedName("english_name")
  private String englishName = null;
  @SerializedName("market_warning")
  private String marketWarning = null;

  /**
   * 업비트에서 제공중인 시장 정보
   **/
  @ApiModelProperty(value = "업비트에서 제공중인 시장 정보")
  public String getMarket() {
    return market;
  }
  public void setMarket(String market) {
    this.market = market;
  }

  /**
   * 거래 대상 암호화폐 한글명
   **/
  @ApiModelProperty(value = "거래 대상 암호화폐 한글명")
  public String getKoreanName() {
    return koreanName;
  }
  public void setKoreanName(String koreanName) {
    this.koreanName = koreanName;
  }

  /**
   * 거래 대상 암호화폐 영문명
   **/
  @ApiModelProperty(value = "거래 대상 암호화폐 영문명")
  public String getEnglishName() {
    return englishName;
  }
  public void setEnglishName(String englishName) {
    this.englishName = englishName;
  }

  /**
   * 유의 종목 여부 - NONE (해당 사항 없음) - CAUTION (투자유의) 
   **/
  @ApiModelProperty(value = "유의 종목 여부 - NONE (해당 사항 없음) - CAUTION (투자유의) ")
  public String getMarketWarning() {
    return marketWarning;
  }
  public void setMarketWarning(String marketWarning) {
    this.marketWarning = marketWarning;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketInfo marketInfo = (MarketInfo) o;
    return (this.market == null ? marketInfo.market == null : this.market.equals(marketInfo.market)) &&
        (this.koreanName == null ? marketInfo.koreanName == null : this.koreanName.equals(marketInfo.koreanName)) &&
        (this.englishName == null ? marketInfo.englishName == null : this.englishName.equals(marketInfo.englishName)) &&
        (this.marketWarning == null ? marketInfo.marketWarning == null : this.marketWarning.equals(marketInfo.marketWarning));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.market == null ? 0: this.market.hashCode());
    result = 31 * result + (this.koreanName == null ? 0: this.koreanName.hashCode());
    result = 31 * result + (this.englishName == null ? 0: this.englishName.hashCode());
    result = 31 * result + (this.marketWarning == null ? 0: this.marketWarning.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketInfo {\n");
    
    sb.append("  market: ").append(market).append("\n");
    sb.append("  koreanName: ").append(koreanName).append("\n");
    sb.append("  englishName: ").append(englishName).append("\n");
    sb.append("  marketWarning: ").append(marketWarning).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
