/**
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "CoreMinimal.h"
#include "SwaggerBaseModel.h"

namespace Swagger 
{

class SWAGGER_API SwaggerTradeApi
{
public:
	SwaggerTradeApi();
	~SwaggerTradeApi();

	void SetURL(const FString& Url);
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	class TradeTickerRequest;
	class TradeTickerResponse;
	class TradeTicksRequest;
	class TradeTicksResponse;
	
    DECLARE_DELEGATE_OneParam(FTradeTickerDelegate, const TradeTickerResponse&);
    DECLARE_DELEGATE_OneParam(FTradeTicksDelegate, const TradeTicksResponse&);
    
    bool TradeTicker(const TradeTickerRequest& Request, const FTradeTickerDelegate& Delegate = FTradeTickerDelegate()) const;
    bool TradeTicks(const TradeTicksRequest& Request, const FTradeTicksDelegate& Delegate = FTradeTicksDelegate()) const;
    
private:
    void OnTradeTickerResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FTradeTickerDelegate Delegate) const;
    void OnTradeTicksResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FTradeTicksDelegate Delegate) const;
    
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
};
	
}
