/**
 * Upbit Open API
 * ## REST API for Upbit Exchange - Base URL: [https://api.upbit.com] - Official Upbit API Documents: [https://docs.upbit.com] - Official Support email: [open-api@upbit.com] 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ujhin942@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerTrade.h"

namespace Swagger 
{

/*
 * SwaggerOrderInfo
 *
 * 
 */
class SWAGGER_API SwaggerOrderInfo : public Model
{
public:
    virtual ~SwaggerOrderInfo() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* 주문의 고유 아이디 */
	TOptional<FString> Uuid;
	/* 주문 종류 */
	TOptional<FString> Side;
	/* 주문 방식 */
	TOptional<FString> OrdType;
	/* 주문 당시 화폐 가격 */
	TOptional<FString> Price;
	/* 주문 상태 */
	TOptional<FString> State;
	/* 마켓의 유일키 */
	TOptional<FString> Market;
	/* 주문 생성 시간 */
	TOptional<FString> CreatedAt;
	/* 사용자가 입력한 주문 양 */
	TOptional<FString> Volume;
	/* 체결 후 남은 주문 양 */
	TOptional<FString> RemainingVolume;
	/* 수수료로 예약된 비용 */
	TOptional<FString> ReservedFee;
	/* 남은 수수료 */
	TOptional<FString> RemainingFee;
	/* 사용된 수수료 */
	TOptional<FString> PaidFee;
	/* 거래에 사용중인 비용 */
	TOptional<FString> Locked;
	/* 체결된 양 */
	TOptional<FString> ExecutedVolume;
	/* 해당 주문에 걸린 체결 수 */
	TOptional<double> TradesCount;
	/* 체결 */
	TOptional<TArray<SwaggerTrade>> Trades;
};

}
